spring:
    hadoop:
        fsUri: hdfs://localhost:8020
        resourceManagerHost: localhost
    yarn:
        appType: XD
        client:
            clientClass: org.springframework.yarn.client.DefaultApplicationYarnClient
            resource:
                memory: 512M
            files:
                - "file:${spring.xd.yarn.app.path}/${spring.xd.yarn.app.zip}"
                - "file:${spring.xd.yarn.am.path}/${spring.xd.yarn.am.jar}"
                - "file:${spring.xd.yarn.config.path}/xd-config.yml"
            launchcontext:
                archiveFile: "${spring.xd.yarn.am.jar}"
            localizer:
                patterns:
                    - "xd-config.yml"
---
spring:
    profiles: admin
    yarn:
        appName: xd-admin
        client:
            launchcontext:
                arguments:
                    -Dspring.profiles.active: "admin"
                    -Dspring.xd.yarn.app.zip: "${spring.xd.yarn.app.zip}"
                    -Dspring.config.location: "./xd-config.yml"
                    --spring.yarn.appmaster.containerCount: "${spring.xd.adminServers:1}"
---
spring:
    profiles: container
    yarn:
        appName: xd-container
        client:
            launchcontext:
                arguments:
                    -Dspring.profiles.active: "container"
                    -Dspring.xd.yarn.app.zip: "${spring.xd.yarn.app.zip}"
                    -Dspring.yarn.applicationDir: "${spring.yarn.applicationDir}"
                    -Dspring.config.location: "./xd-config.yml"
                    --spring.yarn.appmaster.containerCount: "${spring.xd.containers:1}"
