spring:
    yarn:
        endpoints:
            containercluster:
                enabled: true
        appmaster:
            appmasterClass: org.springframework.xd.yarn.XdAppmaster
            keepContextAlive: true
            localizer:
                patterns:
                    - "spring-xd-yarn*.zip"
                    - "servers.yml"
                    - "modules.yml"
                    - "custom-modules.zip"
            containercluster:
                enabled: true
                clusters:
                    admin:
                        projectionType: any
                        projectionAny: "${xd.adminServers:1}"
                        resource:
                            priority: 1
                            memory: "${xd.adminMemory:512M}"
                            virtualCores: 1
                        launchcontext:
                            runnerClass: org.springframework.xd.dirt.server.AdminServerApplication
                            locality: false
                            useYarnAppClasspath: true
                            useMapreduceAppClasspath: true
                            arguments:
                                -Dspring.application.name: "admin"
                                -DxdHomeDir: "./${spring.xd.yarn.app.zip}"
                                -Dspring.config.location: "./servers.yml"
                                -Dxd.module.config.location: "file:./"
                            containerAppClasspath:
                                - "./${spring.xd.yarn.app.zip}/config"
                                - "./${spring.xd.yarn.app.zip}/lib/*"
                                - "./custom-modules.zip"
                    container:
                        projectionType: any
                        projectionAny: "${xd.containers:1}"
                        resource:
                            priority: 2
                            memory: "${xd.containerMemory:512M}"
                            virtualCores: 1
                        launchcontext:
                            runnerClass: org.springframework.xd.dirt.server.ContainerServerApplication
                            locality: false
                            useYarnAppClasspath: true
                            useMapreduceAppClasspath: true
                            arguments:
                                -Dspring.application.name: "container"
                                -DxdHomeDir: "./${spring.xd.yarn.app.zip}"
                                -Dspring.config.location: "./servers.yml"
                                -Dlogging.config: "./${spring.xd.yarn.app.zip}/config/xd-container-logger.properties"
                                -Dxd.module.config.location: "file:./"
                                -Dxd.container.groups: "${xd.container.groups:yarn}"
                            containerAppClasspath:
                                - "./${spring.xd.yarn.app.zip}/config"
                                - "./${spring.xd.yarn.app.zip}/lib/*"
                                - "./${spring.xd.yarn.app.zip}/modules/processor/scripts"
                                - "./custom-modules.zip/modules/processor/scripts"
                                - "./custom-modules.zip"
