spring:
  profiles:
    active: default,hsqldb
  datasource:
    url: jdbc:hsqldb:hsql://${hsql.server.host:localhost}:${hsql.server.port:9101}/${hsql.server.dbname:xdjob}
    username: sa
    password:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
  main:
    show_banner: false
endpoints:
  jolokia:
    enabled: ${XD_JMX_ENABLED:false}
  jmx:
    enabled: false

XD_ANALYTICS: ${analytics:redis}
XD_TRANSPORT: ${transport:redis}
XD_CONTROL_TRANSPORT: ${controlTransport:${XD_TRANSPORT}}
XD_STORE: ${store:redis}
XD_HOME: ${xdHomeDir:..}
XD_JMX_ENABLED: ${jmxEnabled:false}

xd:
  data:
    home: file:${XD_HOME}/data
  config:
    home: file:${XD_HOME}/config
  module:
    home: file:${XD_HOME}/modules
  ui:
    home: file:${XD_HOME}/spring-xd-ui

server:
  port: ${PORT:9393}

---

spring:
  profiles: memory
transport: local
analytics: memory
store: memory
server:
  port: -1
management:
  port: -1

---

spring:
  profiles: rabbit
transport: rabbit

---

spring:
  profiles: cloud

xdHomeDir: .

---

spring:
  profiles: adminServer

---

spring:
  profiles: yarn
  yarn:
    applicationDir: /xd/yarn/xdapps/xdapp/
    applicationsBaseDir: /xd/yarn/xdapps/
    appName: xdapp
    appType: XD 
    fsUri: hdfs://localhost:8020
    rmAddress: localhost:8032
    schedulerAddress: localhost:8030
    client:
      appmasterFile: spring-xd-@application.version@-yarnapp.zip
      runnerClazz: org.springframework.xd.dirt.server.AdminServerApplication
      memory: 500M
      classpath:
        - "./spring-xd-@application.version@-yarnapp.zip/lib/*"
        - "./spring-xd-@application.version@-yarnapp.zip/modules/processor/scripts"
        - "./spring-xd-@application.version@-yarnapp.zip/config"
        - "./spring-xd-@application.version@-yarnapp.zip"
      files:
        - "file:../../yarn/spring-xd-@application.version@-yarnapp.zip"
      arguments:
        - "-Dspring.application.name=admin"
        - "-Dlogging.config=file:./spring-xd-@application.version@-yarnapp.zip/config/xd-admin-logger.properties"
        - "-DPORT=0"
        - "-Dxd.home=./spring-xd-@application.version@-yarnapp.zip"
    appmaster:
      containerCount: 1
      containerFile: spring-xd-@application.version@-yarnapp.zip
      appmasterClazz: org.springframework.xd.yarn.app.xd.appmaster.XdYarnAppmaster
      containerRunner: org.springframework.xd.dirt.server.LauncherApplication
      waitLatch: false
      classpath:
        - "./spring-xd-@application.version@-yarnapp.zip/lib/*"
        - "./spring-xd-@application.version@-yarnapp.zip/modules/processor/scripts"
        - "./spring-xd-@application.version@-yarnapp.zip/config"
        - "./spring-xd-@application.version@-yarnapp.zip"
    container:
      containerClazz: org.springframework.xd.yarn.app.xd.container.XdYarnContainer
      waitLatch: false

---

spring:
  profiles: node
  batch:
    initializer:
      enabled: false
management:
  port: ${PORT:0}
server:
  port: ${PORT:0}

---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver

---
spring:
  profiles: single
transport: local
store: memory
analytics: memory

---
# Redis properties
# (vcap.services.* binds to a service called 'redis' in Pivotal CF)
spring:
  redis:
   port: 6379
   host: localhost

---
# RabbitMQ properties
# (vcap.services.* binds to a service called 'rabbitmq' in Pivotal CF)
spring:
  rabbitmq:
   host: ${vcap.services.rabbitmq.credentials.hostname:localhost}
   port: ${vcap.services.rabbitmq.credentials.port:5672}
   username: ${vcap.services.rabbitmq.credentials.username:guest}
   password: ${vcap.services.rabbitmq.credentials.password:guest}
   virtual_host: ${vcap.services.rabbitmq.credentials.vhost:/}

